config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  root "events#index"

  session_con =
    Rails.env.production? ? "users/sessions" : "users/sessions"

  devise_for :users, controllers: {
    omniauth_callbacks: "callbacks", sessions: session_con
  }

  namespace :api do
    resources :events, only: [:index, :show]
  end

  resources :events do
    post :join, on: :member
    post :unjoin, on: :member
  end
end

app/models/event.rb
# frozen_string_literal: true
# Event
class Event < ApplicationRecord
  include Colorable

  belongs_to :user
  has_many :event_users, dependent: :destroy
  has_many :members, through: :event_users, source: :user

  validates :title, presence: true
  validates :place, presence: true
  validates :start_time, presence: true
  validates :planned_time, presence: true, numericality: true
  validates :timezone, presence: true

  # public scope
  scope :between_period_with_users, lambda { |start_date, end_date|
    with_users
      .since_date(start_date)
      .until_date(end_date)
      .order(start_time: :asc)
  }

  # private scope
  scope :with_users, -> { includes(:user, :members) }
  scope :since_date, lambda { |date|
    where("start_time > ?", Time.zone.parse(date)) if date
  }
  scope :until_date, lambda { |date|
    where("start_time < ?", Time.zone.parse(date)) if date
  }

  def self.init_with_user(attrs, user)
    event = new(attrs)
    event.user = user
    event
  end

  def organizer?(user)
    user.id == user_id
  end

  def joined?(user)
    return true if user.id == user_id
    members.exists?(user.id)
  end

  def finish_time
    start_time + planned_time.hours
  end

  def in_time?
    finish_time > Time.zone.now
  end

  def joiner_names
    members.map(&:mention_name)
  end

  def member_names
    joiner_names.unshift(user.mention_name)
  end

  def human_readable_time
    start_time
  end

  def notify_new_event(target_url)
    SlackWrapper.notify(
      ENV['WEIRDX_NOTIFY_CHANNEL'],
      "새 밋업 일정이 추가되었습니다.\n#{to_slack_message}\n링크: #{target_url}"
    )
  end

  def notify_updated_event(target_url)
    SlackWrapper.notify(
      ENV['WEIRDX_NOTIFY_CHANNEL'],
      "밋업 일정이 변경되었습니다.\n#{to_slack_message}\n링크: #{target_url}"
    )
  end

  def notify_destroyed_event
    SlackWrapper.notify(
      ENV['WEIRDX_NOTIFY_CHANNEL'],
      "밋업 일정이 취소되었습니다.\n#{to_slack_message}"
    )
  end

  def notify_new_member(new_user, target_url)
    SlackWrapper.notify(
      user.mention_name,
      "#{new_user.nickname}님이 '#{title}' 밋업에 참가 신청하셨습니다.\n링크: #{target_url}"
    )
  end

  def notify_cancel_member(new_user, target_url)
    SlackWrapper.notify(
      user.mention_name,
      "#{new_user.nickname}님이 '#{title}' 밋업 참가를 취소하셨습니다.\n링크: #{target_url}"
    )
  end

  private

  def to_slack_message
    "[#{title}]\n" \
    "주최자: #{user.nickname}\n" \
    "시각: #{human_readable_time}\n" \
    "장소: #{place}"
  end

  def to_hex_with
    user&.id || 0
  end
end

app/controllers/api/events_controller.rb
# frozen_string_literal: true
module Api
  # Api::EventsController
  class EventsController < Api::BaseController
    def index
      @events = Event.between_period_with_users(params[:start], params[:end])
    end

    def show
      @event = Event.find(params[:id])
      @user = current_user
    end
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true
# EventsController
class EventsController < ApplicationController
  before_action :permission_check, only: [:edit, :update, :destroy, :copy]

  def index; end

  def show
    event
    @user = current_user
  end

  def join
    message = \
      if event.joined? current_user
        "You already joined! :)"
      else
        event.members << current_user
        event.notify_new_member current_user, event_url(event)
        "Thanks to your join!"
      end
    redirect_to event, notice: message
  end

  def unjoin
    event.members.destroy current_user
    event.notify_cancel_member current_user, event_url(event)
    redirect_to event, notice: "Ok, I believe we could see soon! :)"
  end

  def new
    Time.zone = "Seoul"
    @event = Event.new(start_time: Time.zone.now + 1.hour)
  end

  def edit
    Time.zone = event.timezone
  end

  def create
    Time.zone = event_params[:timezone] || "Seoul"
    @event = Event.init_with_user(event_params, current_user)
    if @event.save
      @event.notify_new_event event_url(@event)
      redirect_to @event, notice: "성공적으로 밋업을 만들었습니다."
    else
      render :new
    end
  end

  def update
    Time.zone = event.timezone

    if event.update(event_params)
      event.notify_updated_event event_url(event)
      redirect_to event, notice: "성공적으로 밋업을 변경했습니다."
    else
      render :edit
    end
  end

  def destroy
    event.notify_destroyed_event unless event.destroy
    redirect_to events_url, notice: "밋업이 취소되었습니다."
  end

  private

  def event_params
    params.require(:event).permit(
      :title, :place, :description,
      :start_time, :planned_time, :timezone
    )
  end

  def event
    @event ||= Event.find(params[:id])
  end

  def permission_check
    raise User::NoPermission unless event.organizer? current_user
  end

  rescue_from ActiveRecord::RecordNotFound do
    redirect_to root_path, notice: "해당하는 이벤트를 찾을 수 없습니다."
  end
end

app/views/events/_form.html.erb
<%= form_for(event, html: {class: "event-form"}) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-xs-11">
      <div class="field form-group">
        <%= f.label :title %>: <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-11">
      <div class="field form-group">
        <%= f.label :place %>: <%= f.text_field :place, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-11">
      <div class="field form-group">
        <%= f.label :description %>:
        <%= f.text_area :description, class: "form-control summernote" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-11">
      <div class="field form-group">
        <%= f.label "시작 예정 시각(현지)" %>:
        <span id="start-time">
          <%= f.datetime_select :start_time, minute_step: 10 %>
          <%= f.time_zone_select :timezone, ActiveSupport::TimeZone.all.sort %>
        </span>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-11">
      <div class="field form-group">
        <div class="col-sm-3">
          <%= f.label "예상 소요 시간" %>:
        </div>
        <div class="col-sm-1">
          <span id="until-hour"><%= f.phone_field :planned_time, class: "form-control" %></span>
        </div>
        <div class="col-sm-2 hour-label">시간</div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-11">
      <div class="actions">
      <% if event.persisted? %>
        <%= f.submit "Update Meetup", class: "btn btn-warning", id: "update-submit" %>
      <% else %>
        <%= f.submit "Create Meetup", class: "btn btn-warning", id: "create-submit" %>
      <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Editing Event</h1>
  </div>
</div>

<%= render "form", event: @event, event_form: @event_form %>

<div class="row">
  <div class="col-xs-12">
    <%= link_to 'Show', @event, class: 'btn btn-primary', style: 'color: #FFF;' %>
    <%= link_to 'Back', events_path, class: 'btn btn-success', style: 'color: #FFF;' %>
  </div>
</div>

app/views/events/index.html.erb
<%= react_component("EventIndex") %>

app/views/events/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>New Event</h1>
  </div>
</div>

<%= render "form", event: @event %>

<div class="row">
  <div class="col-xs-12">
    <%= link_to "Back", events_path, class: "btn btn-success", style: "color: #FFF;" %>
  </div>
</div>

app/views/events/show.html.erb
<div class="show_container">
  <%= react_component("EventShow", id: @event.id) %>

  <div class="row">
    <div class="col-xs-12">
      <% if !@event.organizer?(@user) && @event.in_time? %>
        <% if @event.joined?(@user) %>
            <%= link_to "I cannot go T-T", unjoin_event_path(@event), method: :post, class: "btn btn-warning" %>
        <% else %>
            <%= link_to "Join", join_event_path(@event), method: :post, class: "btn btn-danger" %>
        <% end %>
      <% end %>

      <% if @event.organizer?(@user) %>
        <%= link_to "Edit", edit_event_path(@event), class: "btn btn-info" %>
        <%= link_to "Destroy", @event, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
      <% end %>
      <%= link_to "Back", events_path, class: "btn btn-success" %>
    </div>
  </div>
</div>