config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  root "events#index"

  session_con =
    Rails.env.production? ? "users/sessions" : "users/sessions"

  devise_for :users, controllers: {
    omniauth_callbacks: "callbacks", sessions: session_con
  }

  namespace :api do
    resources :events, only: [:index, :show]
  end

  resources :events do
    post :join, on: :member
    post :unjoin, on: :member
  end
end

app/views/layouts/_notice.html.erb
<% if notice.present? %>
<div class="row">
  <div class="col-xs-12">
    <div id="notice" class="alert alert-warning" style="margin-top: 20px;"><%= notice %></div>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WEIRDMEETUP!</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- FontAwasome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

    <%= csrf_meta_tags %>
    <link rel="icon" href="http://i0.wp.com/blog.weirdx.io/wp-content/uploads/2015/12/icon_black@1x.png?fit=60%2C60" sizes="192x192">
    <link rel="apple-touch-icon-precomposed" href="http://i0.wp.com/blog.weirdx.io/wp-content/uploads/2015/12/icon_black@1x.png?fit=60%2C60">
  </head>
  <body>
    <% if current_user.present? %>
    <div class="container">
      <div class="row">
        <div class="col-md-3 col-xs-6">
          <div class="nav-bar">
            <%= link_to "Go to Index", events_path, class: "btn btn-default" %>
            <%= link_to "New Event", new_event_path, class: "btn btn-success" %>
          </div>
        </div>
        <div class="col-md-offset-6 col-md-3 col-xs-6">
          <div class="nav-bar">
            <%= link_to "Issue or Bug?", "https://github.com/riseshia/cal4w/issues", class: "btn btn-info", target: "_blank" %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, type: "submit", class: "btn btn-danger" %>
          </div>
        </div>
      </div>
    </div>
    <% end %>

    <div class="container">
      <%= render "layouts/notice" %>
      <%= yield %>
    </div>
  </body>
</html>